node {
    try {
        stage('Checkout') {
            checkout scm
        }

        // Kita pake image Maven buat nge-build Java
        // Mirip kayak tadi pake Node image buat React
        docker.image('maven:3.8.6-openjdk-11-slim').inside {
            
            stage('Build') {
                echo 'Building Java App...'
                // Perintah Maven buat build jar (-B biar gak cerewet log-nya)
                sh 'mvn -B -DskipTests clean package'
            }

            stage('Test') {
                echo 'Running Unit Tests...'
                // Perintah Maven buat test
                sh 'mvn test'
            }
        }
    } catch (e) {
        currentBuild.result = 'FAILURE'
        throw e
    }
}
